"use client"

import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Download, ThumbsUp, ThumbsDown, Minus, RotateCcw, ArrowLeft } from "lucide-react"
import { useState } from "react"

interface FinalPageProps {
  onRestart: () => void
  onBack: () => void
}

export function FinalPage({ onRestart, onBack }: FinalPageProps) {
  const [isDownloading, setIsDownloading] = useState(false)
  const [feedbackGiven, setFeedbackGiven] = useState<string | null>(null)

  const handleDownloadReport = async () => {
    setIsDownloading(true)

    // Simulate PDF generation
    setTimeout(() => {
      // Create a mock PDF download
      const reportContent = `
SEPTOCTOR - Neonatal Sepsis Risk Assessment Report
Generated: ${new Date().toLocaleString()}

PATIENT INFORMATION:
- Assessment Date: ${new Date().toLocaleDateString()}
- Risk Level: Moderate Risk
- Overall Score: 7.2/10

SCORING SYSTEMS:
- NEOMOD Score: 6.8/10
- NOSEP Score: 7.1/10  
- SNAP-II Score: 6.9/10
- CRIB-II Score: 7.5/10
- TRIPS Score: 7.0/10

RECOMMENDATIONS:
- Close monitoring recommended
- Consider antibiotic prophylaxis
- Frequent vital sign assessment
- Laboratory follow-up in 6-12 hours

This report was generated by Septoctor AI v1.0
      `

      const blob = new Blob([reportContent], { type: "text/plain" })
      const url = window.URL.createObjectURL(blob)
      const a = document.createElement("a")
      a.href = url
      a.download = `septoctor-report-${new Date().toISOString().split("T")[0]}.txt`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      window.URL.revokeObjectURL(url)

      setIsDownloading(false)
    }, 2000)
  }

  const handleFeedback = (type: string) => {
    setFeedbackGiven(type)
    alert(`Thank you for your feedback! Your "${type}" response has been recorded and will help improve our AI model.`)
  }

  return (
    <div className="max-w-4xl mx-auto px-4">
      <div className="mb-4 md:mb-6">
        <Button
          variant="ghost"
          onClick={onBack}
          className="text-white hover:text-white hover:bg-white/10 flex items-center gap-2 min-h-[44px]"
        >
          <ArrowLeft className="w-4 h-4" />
          <span className="hidden sm:inline">Back to Results</span>
          <span className="sm:hidden">Back</span>
        </Button>
      </div>

      <div className="text-center mb-6 md:mb-8">
        <h2 className="text-2xl md:text-3xl font-bold text-white mb-2">Assessment Complete</h2>
        <p className="text-sm md:text-base text-white/80">Download your report and provide feedback</p>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-2 gap-4 md:gap-6">
        {/* Download Report */}
        <Card className="bg-white/95 backdrop-blur-sm border-0 shadow-xl">
          <CardHeader>
            <CardTitle className="flex items-center text-lg md:text-xl">
              <Download className="w-4 h-4 md:w-5 md:h-5 mr-2 text-primary" />
              Download Report
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="bg-gradient-to-r from-primary/5 to-accent/5 rounded-lg p-4 md:p-6">
              <h3 className="font-semibold mb-2 text-base md:text-lg">Comprehensive Assessment Report</h3>
              <p className="text-xs md:text-sm text-muted-foreground mb-4">
                Complete analysis including all scoring systems, risk factors, and recommendations
              </p>

              <div className="space-y-2 text-xs md:text-sm mb-4">
                <div className="flex justify-between">
                  <span>Patient Data:</span>
                  <Badge variant="outline">Included</Badge>
                </div>
                <div className="flex justify-between">
                  <span>Risk Scores:</span>
                  <Badge variant="outline">All 5 Systems</Badge>
                </div>
                <div className="flex justify-between">
                  <span>AI Analysis:</span>
                  <Badge variant="outline">Detailed</Badge>
                </div>
                <div className="flex justify-between">
                  <span>Recommendations:</span>
                  <Badge variant="outline">Clinical</Badge>
                </div>
              </div>

              <Button
                className="w-full bg-gradient-to-r from-primary to-accent min-h-[44px]"
                onClick={handleDownloadReport}
                disabled={isDownloading}
              >
                <Download className="w-4 h-4 mr-2" />
                {isDownloading ? "Generating PDF..." : "Download PDF Report"}
              </Button>
            </div>
          </CardContent>
        </Card>

        {/* Doctor Feedback */}
        <Card className="bg-white/95 backdrop-blur-sm border-0 shadow-xl">
          <CardHeader>
            <CardTitle className="text-lg md:text-xl">Doctor Feedback</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-xs md:text-sm text-muted-foreground mb-4">
              Your feedback helps improve our AI model accuracy
            </p>

            <div className="space-y-3">
              <h4 className="font-medium text-sm md:text-base">How accurate was this assessment?</h4>

              <div className="grid grid-cols-1 gap-3">
                <Button
                  variant={feedbackGiven === "agree" ? "default" : "outline"}
                  className="justify-start h-auto p-3 md:p-4 hover:bg-medical-success/10 hover:border-medical-success bg-transparent min-h-[44px]"
                  onClick={() => handleFeedback("agree")}
                >
                  <ThumbsUp className="w-4 h-4 md:w-5 md:h-5 mr-3 text-medical-success flex-shrink-0" />
                  <div className="text-left">
                    <div className="font-medium text-sm md:text-base">Agree</div>
                    <div className="text-xs text-muted-foreground">Assessment matches clinical judgment</div>
                  </div>
                </Button>

                <Button
                  variant={feedbackGiven === "partially agree" ? "default" : "outline"}
                  className="justify-start h-auto p-3 md:p-4 hover:bg-medical-warning/10 hover:border-medical-warning bg-transparent min-h-[44px]"
                  onClick={() => handleFeedback("partially agree")}
                >
                  <Minus className="w-4 h-4 md:w-5 md:h-5 mr-3 text-medical-warning flex-shrink-0" />
                  <div className="text-left">
                    <div className="font-medium text-sm md:text-base">Partially Agree</div>
                    <div className="text-xs text-muted-foreground">Some aspects need refinement</div>
                  </div>
                </Button>

                <Button
                  variant={feedbackGiven === "disagree" ? "default" : "outline"}
                  className="justify-start h-auto p-3 md:p-4 hover:bg-medical-danger/10 hover:border-medical-danger bg-transparent min-h-[44px]"
                  onClick={() => handleFeedback("disagree")}
                >
                  <ThumbsDown className="w-4 h-4 md:w-5 md:h-5 mr-3 text-medical-danger flex-shrink-0" />
                  <div className="text-left">
                    <div className="font-medium text-sm md:text-base">Disagree</div>
                    <div className="text-xs text-muted-foreground">Assessment needs significant improvement</div>
                  </div>
                </Button>
              </div>
            </div>

            <div className="pt-4 border-t">
              <Button onClick={onRestart} variant="outline" className="w-full bg-transparent min-h-[44px]">
                <RotateCcw className="w-4 h-4 mr-2" />
                Start New Assessment
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Summary Stats */}
      <Card className="mt-4 md:mt-6 bg-white/95 backdrop-blur-sm border-0 shadow-xl">
        <CardContent className="p-4 md:p-6">
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 md:gap-4 text-center">
            <div>
              <div className="text-xl md:text-2xl font-bold text-primary">5</div>
              <div className="text-xs md:text-sm text-muted-foreground">Scoring Systems</div>
            </div>
            <div>
              <div className="text-xl md:text-2xl font-bold text-accent">47</div>
              <div className="text-xs md:text-sm text-muted-foreground">Parameters Analyzed</div>
            </div>
            <div>
              <div className="text-xl md:text-2xl font-bold text-medical-teal">2.3s</div>
              <div className="text-xs md:text-sm text-muted-foreground">Processing Time</div>
            </div>
            <div>
              <div className="text-xl md:text-2xl font-bold text-primary">98.7%</div>
              <div className="text-xs md:text-sm text-muted-foreground">Model Confidence</div>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
